### ISSUE TITLE
CLI - missing functionality (olympia)

### ISSUE THREAD

**Issue by Lezek123** [Joystream/joystream#2254]
### Olympia-related

Functionality available in `Olympia` runtime but not part of Pioneer 2 wireframes (for now I'm excluding content directory due to pending `Sumer` rework)

**Forum working group:**
- [ ] Creating categories/subcategories by lead (`create_cateogry`)
- [ ] Assiging moderators to categories by lead (`update_category_membership_of_moderator`)
- [ ] Updating category archival status by lead / moderator (`update_category_archival_status`)
- [ ] Updating thread archival status by lead / moderator (`update_thread_archival_status`)
- [ ] Deleting categories by lead / moderator (`delete_category`)
- [ ] Deleting threads by lead / moderator (`delete_thread`)
- [ ] Moving threads to different category by lead / moderator (`move_thread_to_category`)
- [ ] Moderating (slashing) threads by lead / moderator (`moderate_thread`)
- [ ] Moderating (removing) posts by lead / moderator (`moderate_post`)
- [ ] Setting sticked threads by lead / moderator (`set_stickied_threads`)

**Members/accounts:**
- ~~Update member root / role account (`update_accounts`)~~
- [ ] Setup staking accounts (`add_staking_account_candidate`, `confirm_staking_account`) _**This is already partially implemented in CLI for the purpose of `working-groups:apply`. I couldn't find related wireframes, but it would also be required ie. when creating a new proposal (which is part of Pioneer 2)**_
- [ ] Buying membership (this is part of Pioneer, but would be very useful to have it in CLI too)
- ~~Setting account memo~~

**Validation/nomination**
It's possible to this via https://polkadot.js.org/apps by injecting Joystream json types and connecting to a Joystream node, but it can be also included as part of the CLI:
- [ ] Setting up a validator
- [ ] Setting up a nominator
- [ ] Exploring active validators / nominators
- [ ] Claiming rewards

**Membership working group:**
- [ ] Updating verification status of members by workers (`update_profile_verification`)

**Working groups (general):**
- [ ] Setting group status text (`set_status_text`)

**Blogs**

I didn't find those in wireframes, but I'm not sure if this should be part of the CLI

**Query node integration**

Query node integration would be required in order to, for example, display member handles, opening/application metadata etc.
- [x] setting query node endpoint and initializing Apollo client
- [x] querying and displaying membership handles

### Other CLI nice-to-haves

- automated testing
- improving scriptability
- perhaps some baisc interface for executing sudo actions (can be just something like `api:tx` with `--sudo` flag)
