### ISSUE TITLE
Tracking issue for runtime gateway

### ISSUE THREAD

**Issue by conectado** [Joystream/joystream#2364]
## In this issue I'll track the needed work for the runtime part of the specification in #2089 

To be able to implement the gateway spec in the runtime we need
* [x] Add gateway working group (30m)
* [x] Add (generic) service provider working group (30m)
* [ ] Gateway module (30h)
* [ ] Gateway module tests (10h)
* [ ] Update Proposals (1h)
