### ISSUE TITLE
Storage v2 distribution - progress tracking

### ISSUE THREAD

**Issue by Lezek123** [Joystream/joystream#2543]
## CLI
- [X] General accounts/api setup

**Lead:**
- [X] create bucket family
- [x] delete bucket family
- [X] create bucket
- [X] update distribution buckets for bag
- [x] update distribution bucket status (`acceptsNewBags` flag) - _shouldn't this be done by worker?_
- [x] delete distribution bucket
- [x] update distribution buckets per bag limit
- [x] update distribution bucket mode (`distributing` flag)
- [x] update families in dynamic bag creation policy (number of buckets per family that should store given dynamic bag)
- [x] invite distribution bucket operator
- [x] cancel distribution bucket operator invitation
- [x] remove distribution bucket operator
- [x] set bucket family metadata

**Operator:**
- [x] accept distribution bucket invitation
- [x] set distribution operator metadata

**Inspecting chain state / query node data:**

It's not obvious how much of this, if anything should be part of the CLI (alternatively this can be checked using query node playground and a tool for inspecting substrate chain state like `polkadot-js/apps`, but this will be less convenient):
- checking current distribution policies for dynamic bags (chain / possibly query-node)
- checking current distribution buckets per bag limit (chain / possibly query-node)
- inspecting current buckets metadata (query node)
- inspecting current buckets status (acceptingNewBags / distributing) (query-node / chain)
- inspecing bags in bucket (query-node / chain)
- inspecting data objects in bag (query-node / chain)
- etc.

## Protobuf
- [x] Storage bucket metadata format
- [x] Distributor bucket metadata format
- [x] Distributor bucket family metadata format
- [x] Merge with master's protobuf lib (implies switch to `protobufjs`)

## Query node

- [X] Storage schema & mappings (https://github.com/Joystream/joystream/pull/2515)
- [x] Distribution schema & mappings
- [x] Metadata handling
- [ ] Update Hydra once https://github.com/Joystream/hydra/issues/448 is resolved
- [ ] Merge `storage-v2` and `content-directory` mappings once `master` is merged to `storage-v2` branch
- [ ] `DataObject.type`

## Distributor Node

**API:**
- [X] data object request endpoint
- [X] download requested data objects from storage node when missing (picking first-response node and creating a queue of alternative endpoints to try on failure)
- [x] limit number of initial requests made when object is missing (currently "check" requests are made to every storage provider that's supposed to store given object)
- [ ] bandwidth / simultaneous connections management (limits, prioritizing)
- [x] proxying requests while downloading data objects or streaming from file (depending on `Range`)
- [ ] controlling buckets served on a given instance via an authorized endpoint
- [x] allowing `'all'` buckets config option - distributing all buckets that are part of runtime worker assignment 
- [X] simple status endpoint
- [X] support `HEAD` requests on data object endpoint (for the purpose of checking headers without triggering LRU cache state update and potential data object fetching)
- [X] `/buckets` endpoint exposing supported buckets

**State / cache / storage**
- [X] persistent object -> file type / extension association
- [X] `LRU-SP` cache policy
- [ ] dropping data objects when no longer supported (no longer part of distributed buckets)
  _It's not yet clear when should it happen - on request? (probably simplest approach). In a separate job set up via `setInterval` and performed every X seconds?_
- [ ] storing objects in a directory structure that would faciliate faster access
- [ ] simplification: storing objects by `dataObjectId` instead of hashes (?)

**Startup, cleanup, data integrity:**
- [X] recreating object -> file type association on startup when missing
- [X] waiting for pending downloads to finish on exit
- <s>resuming pending downloads / downloading missing data objects</s>
- [ ] a tool to run full data integrity check & fix any potential issues (checking data objects hashes etc.)

**Logging**
- [x] adjust logging levels
- [x] support for custom elasticsearch endpoint

**Initial sync**
- <s>initial sync of joining nodes - use an external source to determine populary of the content in order to initialize data objects cache (Orion? other nodes?)
_What if a node already has a full cache and is  is tasked with storing a completely new bucket? Should it still try to guess and pre-fetch some potentially popular content then?_</s>

_**Other features to conside**r_
- <s>fetching data between distributor nodes</s>

## Testing

- [ ] handling massive spikes of simultaneous requests
- [ ] handling random node shutdowns
- [ ] handling data corruption
- ...
