### ISSUE TITLE
Ops and R&D Tasks

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/joystream#3054]
## Context
This is a tracking/ placeholder temp issue to triage the actions and tasks from the latest retrospective for the network team held on 13th Jan 22.

[Link to the Miro Board >](https://miro.com/app/board/uXjVOZwmt_k=/)

## Tasks
:one:  **Critical to start right now**

all

* [x] Check if in the current PRs we have made progress on assigning more than 1 person for review. Action point was "Dual reviews of  API interfaces PRs."

Lezek123 

* [ ] Review Old vs New Schema for Memberships
* [ ] Review Old vs New Schema for Faucet

:two:  **Part of Olympia scope**
all

* [x] Log changes spanning all key updates since designs via GH file called "Changelog". 

Lezek123 mnaamani 

* [x] Do CI tasks earlier

:three:  **After Olympia** 

* [ ] #3037 
* [x] #1593
* [ ] #1595
* [ ] #3036 
* [ ]  #3035 
* [ ] #3017  +  #2563

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201703380142370/1201703507949489) by [Unito](https://www.unito.io)
