### ISSUE TITLE
Tracking Issue: content <-> storage integration cleanup

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#3082]
* [x] https://github.com/Joystream/joystream/issues/3071
* [x] https://github.com/Joystream/joystream/issues/3075
* [x] https://github.com/Joystream/joystream/issues/3076
* [x] https://github.com/Joystream/joystream/issues/3077
* [x] https://github.com/Joystream/joystream/issues/3078
* [x] https://github.com/Joystream/joystream/issues/3079
* [x] https://github.com/Joystream/joystream/issues/3083
* [x] https://github.com/Joystream/joystream/issues/3081

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201958687417145/1201958631338934) by [Unito](https://www.unito.io)

**Comment by dobertRowneySr** [comment]
- [x] #2677

**Comment by bedeho** [comment]
I dont think this lat issue #2677 fits in there, its not about integration with storage?
