### ISSUE TITLE
Finalize channel payouts in runtime

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#3263]
# Background
This has already been implemented in the content directory

https://github.com/Joystream/joystream/issues/2365

# Proposal
First some simple naming stuff. Lets refer to the act of using merkle proof as _claiming_, the event of having some amount credited to you in the merkle root as _earned_ and the act of transferring funds from your channel account (read below) to some other account as _withdrawing_. 

* [x] Rename `PullPaymentElement::cumulative_payout_claimed` to `cumulative_reward_earned`.
* [x] Rename `ChannelRecord::cumulative_payout_earned` to `cumulative_reward_claimed`.
* [x] Add new `withdraw_from_channel_balance` extrinsic which allows the channel owner to actually withdraw funds from the channel account to some other account. It should not affect `cumulative_reward_claimed`, only balance of account. Collaborator members cannot call this, only owner.
* [x] Add a new extrinsic `claim_and_withdraw`, which is an atomic invocation of `claim_channel_reward` & `withdraw_from_channel_balance`, **but remember to only emit one new event**. Collaborator members cannot call this, only owner.

Then the more substantive stuff:

* [x] (Done by @ignazio-bovo ) Replace channel accounts from being optional external accounts to being hard-coded internal module accounts, one unique account per channel.
* [x] Add proposal which can block all, and unblock, cashout attempts.
* [x] ~Add an extrinsic, which lead can invoke, to block/unblock specific individual channels from doing cashouts (or revenue splits).~
* [x] Drop `MaxRewardAllowed`, semantics are not that useful, instead introduce a `MaxCashoutAllowed`, analogous to `MinCashoutAllowed`, which only looks at the actual `cashout` value, not the total. Neither value can be set by lead, only council through proposal below.
* [x] Add council proposal to update merkle root, initiate payload upload to council storage bag, and extend to support simultaneously
  * possible new value for `MinCashoutAllowed`, not required.
  * possible new value for `MaxCashoutAllowed`, not required.
  * possible to credit content WG budget some amount, not required.
  * possible to automatically unblock cashouts if they current are blocked, not required, and if they are already blocked, there should be no error executing proposal none the less.
* [x] A new council proposal for only setting `MinCashoutAllowed` & `MaxCashoutAllowed`, not updating the payout.
* [x] Add mutation safe barrier.

# Deployment
These changes will have sufficiently far reaching consequences w.r.t. query node, Atlas, etc., so that we will have to deploy in a runtime upgrad post `Olympia`.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201958687417145/1201958613397743) by [Unito](https://www.unito.io)

**Comment by bedeho** [comment]
Replying to some questions in public for context:

> There is currently no relation between one and the other, since channel cashouts are paid with freshly minted tokens, should this logic be changed?

Yes I think this is a mistake, all minting has to be constrained by one global budget. But now that you mention it, it probably makes sense to use the council budget, rather than content WG, because otherwise one ends up having to give a possible super large budget to the WG, despite the lead not being supposed to spend it. So That is a mistake on my end in this issue.

> Does this proposal replace the current model where content WG lead controlls MinCashoutAllowed, MaxCashoutAllowed and commitment (merkle root) or complement it?

Replace :)

**Comment by Lezek123** [comment]
Done in https://github.com/Joystream/joystream/pull/3444
