### ISSUE TITLE
NFT query node - tracking issue

### ISSUE THREAD

**Issue by ondratra** [Joystream/joystream#3302]
Tasks needed to fully support NFTs by QN:

* [ ] https://github.com/Joystream/joystream/issues/3301
* [ ] https://github.com/Joystream/joystream/issues/3461
* [x] https://github.com/Joystream/joystream/issues/3277 (just QN part of the ticket)
* [x] https://github.com/Joystream/joystream/issues/3300
* [x] https://github.com/Joystream/joystream/issues/3314

Following issues (likely) needs to be fixed in Hydra:
* [ ] https://github.com/Joystream/joystream/issues/3342

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201899819496282/1201899833625709) by [Unito](https://www.unito.io)

**Comment by kdembler** [comment]
Additionally:

- [ ] https://github.com/Joystream/joystream/issues/3342
- [ ] https://github.com/Joystream/joystream/issues/3343
- [ ] https://github.com/Joystream/joystream/issues/3381
- [ ] https://github.com/Joystream/joystream/issues/3502
- [ ] https://github.com/Joystream/joystream/issues/3568
- [ ] https://github.com/Joystream/joystream/issues/3567
- [x] https://github.com/Joystream/joystream/issues/3312
- [x] https://github.com/Joystream/joystream/issues/3426
- [x] https://github.com/Joystream/joystream/issues/3424
- [x] https://github.com/Joystream/joystream/issues/3344
- [x] https://github.com/Joystream/joystream/issues/3304
- [x] https://github.com/Joystream/joystream/issues/3305
