### ISSUE TITLE
CRT: revenue split - merge

### ISSUE THREAD

**Issue by dobertRowneySr** [Joystream/joystream#3711]
Merge old #3629 into current `ephesus` branch

##### TODOs:
* [x] update vesting schedule logic to existing one in CRT sales
* [x] update balance handling business logic
* [x] remove redundant errors
* [x] update tests if needed
* [x] review doc-comments

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201738706333715/1202239858126032) by [Unito](https://www.unito.io)

**Comment by bedeho** [comment]
all creator token work should be part of audit project, not ephesus, make sure this applies across all open issues.
