### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by metmirr** [Joystream/joystream#383]
#### Indexer
- [x] Add information about last processed event #310 
- [x] Basic database operations (CRUD)
- [x] Use database transactions to make changes on database #310 
- [x] Start from a specific block number
- [x] Safe entity types for `db` module
- [x] Make mappings transaction safe. All database operations for a mapping should be done in a single database transaction

#### Mappings
- [x] Add another related event. One database table gets updates from multiple events.
- [ ] Unit tests

#### GraphQL
- [x] Change schema defination format from JSON to something more readable and compatible with TheGraph #313 
- [ ] Propagate description of fields and types to GraphQL
- [ ] Relationships between types

#### CLI
- [x] Add option to set last processed event to genesis (purging chain will cause error: `Provided block is ahead of chain.`)
- [ ] Update readme for requirement installation

#### Deployment
- [ ] Deployment for Indexer and GraphQL server #311

**Comment by bedeho** [comment]
Superseded by https://github.com/orgs/Joystream/projects/15
