### ISSUE TITLE
Re-enable and fix runtime upgrade CI check

### ISSUE THREAD

**Issue by mnaamani** [Joystream/joystream#4555]
The github workflow job https://github.com/Joystream/joystream/blob/ephesus/.github/workflows/run-network-tests.yml#L188 needs to be updated to test against the latest mainnet runtime. The associated tooling may also not work correctly in `tests/network-tests/run-migration-tests.sh` and should be updated.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202078489349362/1203779180308558) by [Unito](https://www.unito.io)

**Comment by dobertRowneySr** [comment]
# Intro & Scope
Substrate forkless updates can be classified in pure *runtime-migration* and *data-migration*, according whether mutation of the *existing* on-chain state is needed, and thus some on-chain transition logic `old_state -> new_state` is needed.
## Fork-off Script
1. Downloads the complete storage state from a live substrate chain from a ws endpoint
2. Generates empty chainspec
3. Fork-off populates the chainspec with the downloaded storage
4. starts node with current live storage
5. Test transition runtime logic by applying a Substrate fork-less upgrade
## Forkless upgrade
via the [frame system `set_code` extrinsic](https://docs.substrate.io/tutorials/get-started/upgrade-a-running-network/), in our case via a governance proposal
# TODOs
Current runtime upgrade mainnet -> ephesus is a pure runtime migration. However if we want to fix this script now: 

- [x] Add a flag that select the fork-off script whether *data-migration* is needed to be tested or not
- [x] remove the root key from the sudo pallet condition if `Alice` account is specified (since we don't use the sudo pallet anymore)
- [ ] update Joystream rpc endpoints from where storage is obtained for the fork-off script
- [ ] Replace `runtime.wasm` swap with runtime upgrade integration test (with the appropriate proposal scenario)
