### ISSUE TITLE
Runtime upgrade with hash vs WASM image

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#4637]
# Background

Currently, runtime upgrades require submitting the WASM image as part of creating the proposal. This means that, if an upgrade must be done to solve a sensitive security problem - where it may be in the interest of the DAO to perform the upgrade without revealing the source in advance, then anyone will be able review the WASM image and work out the vulnerability. With a high constitutionality, currently of 4, this leaves many months of time to perform such an analysis. 

# Background

Introduce a new runtime "secret" runtime ugprade where only hash is submitted upon creation, and actual upgrade can be performed in a designated time window after the proposal is executed by sending a new extrinsic, with the WASM blob as payload that must be preimage of hash. There probably should only ever be one such hash commitment for an upgrade in flight at any given time, so any prior active commitment must be overwritten.

# TODO

- [ ] prepare rough specification, get feedback at `idea` stage of JIP
- [ ] create upgrade JIP
- [ ] write reference implementation & tests (unit+integration)
