### ISSUE TITLE
Forum Progress Tracking

### ISSUE THREAD

**Issue by siman** [Joystream/joystream#47]
This issue covers the user stories for the Forum module that we would like to see implemented in Acropolis release.

### All (members + non-members)

- As a user I can view a list of top level topic categories.
  - [x] UI components
  - [x] Runtime
  - [x] Integration: UI + Runtime
- As a user I can open topic categories and view threads, by title and date of submission, and subtopic categories.
  - [x] UI components
  - [x] Runtime
  - [x] Integration: UI + Runtime
- As a user I can view a paginated list of posts in a thread.
  - [x] UI components
  - [x] Runtime
  - [x] Integration: UI + Runtime
- As a user I can view a post, in terms of author, date of submission and text.
  - [x] UI components
  - [x] Runtime
  - [x] Integration: UI + Runtime

### Member

- As a member I can create a new thread in a category, with a title and text.
  - [x] UI components
  - [x] Runtime
  - [x] Integration: UI + Runtime
- As a member I can compose a post in markdown and submit to a thread.
  - [x] UI components
  - [x] Runtime
  - [x] Integration: UI + Runtime
- As a member I can edit the text of a post.
  - [x] UI components
  - [x] Runtime
  - [x] Integration: UI + Runtime
  
### Forum Sudo

- As forum sudo create a subcategory.
  - [x] UI components
  - [x] Runtime
  - [x] Integration: UI + Runtime
- As forum sudo I can archive and/or delete a category.
  - [x] UI components
  - [x] Runtime
  - [x] Integration: UI + Runtime
- As forum sudo I can moderate a post.
  - [x] UI components
  - [x] Runtime
  - [x] Integration: UI + Runtime

### Sudo

- As sudo I can make a member a forum sudo.
  - [x] UI components
  - [x] Runtime
  - [x] Integration: UI + Runtime
- As sudo I can remove a forum sudo.
  - [x] UI components
  - [x] Runtime
  - [x] Integration: UI + Runtime

### Integration

- [x] Module into test runtime

**Comment by bwhm** [comment]
The conclusion from last informal forum release meeting was:

@bedeho will finalize runtime before Friday the 31st of May.
@siman will integrate UI+runtime in time for [sub-system test](https://github.com/Joystream/joystream/tree/master/testnets/acropolis#sub-system-test) of the forum on the 5th of June, 1200CEST.

**Comment by bwhm** [comment]
Update, 28.05.19:

@bedeho will try to ship the runtime code for review on Friday the 31th He will then start integrating it with the athens runtime [v5.3.0](https://github.com/Joystream/joystream/tree/master/testnets/acropolis#runtime).

@siman will most likely be unavailable most of Friday the 31th, but will be able to review.

In order to save time, @bedeho will not have to produce full unit test coverage for Friday, and delegate some of it to @siman.

**Comment by bwhm** [comment]
Update, 04.06.19:

@bedeho will finalize runtime integration on Thursday the 6th.

@siman will integrate runtime with UI, for sub-system test on the 11th.

**Comment by bwhm** [comment]
## Sub-system test

Test was performed 17.06.19, in line with the latest [live-milestones](https://github.com/Joystream/joystream/tree/master/testnets/acropolis#live-milestones).

* A few (known) features were missing:
   1. Archiving/deleting of posts.
   2. Editing of OP (the body of the the new thread)
   3. The intention was to have a hierarchy of three categories: "root", "sub1" and "sub2". The third one did not work, but we considered this a non-issue.
* A few (known) UI/UX improvements were discovered.
   1. Buttons with functionality restricted to `forum sudo` was shown for all users.
   2. After posting/editing/moderating, you have to go back manually to see the changes.
   3. Some naming could be improved.

**Comment by bwhm** [comment]
## Final Test

The final test was performed 20.06.19, in line with the latest [live-milestones](https://github.com/Joystream/joystream/tree/master/testnets/acropolis#live-milestones).

In addition to myself and @siman, two community members participated in testing.

* Ref the missing features in the post above:
   1. Archiving/deleting works.
   2. Not resolved.
   3. Not attempted to resolve.

* Ref UI/UX:
   1. Some buttons are still visible that "shouldn't" be.
   2. Not resolved.
   3. Partially resolved.
   4. Resolved.

All in all, the forum works well, and the UI/UX stuff can be improved inflight if necessary.

**Comment by bwhm** [comment]
Outstanding issues:
- Don't show `unarchive` for non-sudo users
- Show `member` nickname instead of `key` for posts/moderator/creator
- Make the `Moderator` change when the forum-sudo changes?
- Remove the dropdown showing `Add subcat, archive, delete` for non forum-sudo.
- ...

**Comment by bedeho** [comment]
This is done, closing.
