### ISSUE TITLE
Tracker: Runtime CRT work for `crt-1` release

### ISSUE THREAD

**Issue by dobertRowneySr** [Joystream/joystream#4748]
There are current 3 PRs that needs to be reviewed into `crt_release` (which is an old branch used as a base for all CRT work).
These PR are based one on top of another, hence they must be reviewed in the following order:

Relevant PR: #4871 

- [x]  remove symbol map from runtime #4789 
- [x] Avoid that Amm and revenue split being active #4783
- [x] update all CRT metadata #4713 
- [x] remove the deadline parameter from amm extr.s #4483 
- [x] both module account and amm treasury account are guaranteed to be initialised with `ExistentialDeposit` #4198 
- [x] update with nara #4876
- [ ] Settle debate on default value for Amm params #4488 
- [x] benchmark Amm extrinsics #4446 
- [x] merge changes for #4378 

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1204404358291458/1204523048036086) by [Unito](https://www.unito.io)

*Updated* 2023.05.04 15:55 CEST

**Comment by ignazio-bovo** [comment]
I believe that this should be closed, as on the latest meeting we agreed that nara and crt are going on different releases

**Comment by mnaamani** [comment]
completed in https://github.com/Joystream/joystream/pull/4871
