### ISSUE TITLE
Rome (Content Directory Only) Release Redux

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#90]
# Rome (Content Directory Only) Release Redux

### Introduce a better content system

- Members can create a creator profile and publish content under profile.

- There is a curation working group policed by sudo.

- 3 content types at launch in runtime, and supported by Pioneer.

- 1 new content type after release, updating both runtime and Pioneer.

- Migrate some objects to a new schema after release, and update Pioneer to work with multiple versions.

### Engage community to understand Rome and join us in the future

- 50 new creator profiles.

- 10 curators in the working group.

- 1000 content uploads across all content categories.

----

## Tracking Issues

NB: Missing information about who does what

#### Specify/Design

- [ ] New staking module
- [ ] New rewards module
- [ ] New version data store module
- [ ] Content directory module(s): integrates with staking+rewards+data modules
  - _Open question here about how to deal with positions, applications, firings, etc._
- [ ] Curation module(s): integrates with staking+rewards modules
  - _Open question here about how to deal with positions, applications, firings, etc._
  - _The primary objective here is just to have the curators edit metadata and content visibility, nothing more. This can get much more involves in the future, for more accountability, but not now._
- New content types (both at and after launch)
  - [ ] Decide on actual type to support, based on availability of content and richness of schemas.
  - [ ] Determine specific schemas.

#### Implement in Runtime

- [ ] Staking capability for curators: SND uses old staking system!
- [ ] Rewards module
- [ ] Version data store
- [ ] Content directory module(s)
- [ ] Curation module(s)

#### Implement in Pioneer

All major screens and flows should be drafted as super quick (Balsamiq) mockups, for review & discussion, before getting implemented.

##### Creator profile

- Extend membership flow: how you setup a creator profile
  - [ ] mockup
  - [ ] components & styling
  - [ ] state & backend integration
- Third party view of profile: e.g. see all content categorised, cover photo
  - [ ] mockup
  - [ ] components & styling
  - [ ] state & backend integration
- Owner view + editing flow
  - [ ] mockup
  - [ ] components & styling
  - [ ] state & backend integration

##### Curator role

- View status of curator group: list of actors, curation stats.
  - [ ] mockup
  - [ ] components & styling
  - [ ] state & backend integration
- Joining flow
  - [ ] mockup
  - [ ] components & styling
  - [ ] state & backend integration
- Policing flow:
  - [ ] xxx

##### Content Directory

A top level overview view of the entire directory: should we have featured content or creators?
  - [ ] mockup
  - [ ] components & styling
  - [ ] state & backend integration

##### Content

This must be defined _for each type_, refine later when types are decided.
  - Overview of subsection of specific content type: no search for now, just pagination!
    - [ ] mockup
    - [ ] components & styling
    - [ ] state & backend integration
  - Item view & playback experience for creator
    - [ ] mockup
    - [ ] components & styling
    - [ ] state & backend integration
  - Item view & playback experience for third party
    - [ ] mockup
    - [ ] components & styling
    - [ ] state & backend integration
  - Item view & playback experience for curator: show extra information, like schema related stuff ..
    - [ ] mockup
    - [ ] components & styling
    - [ ] state & backend integration
  - Publishing flow
    - [ ] mockup
    - [ ] components & styling
    - [ ] state & backend integration

## Get creator profiles

A competition where we pay X each new content published.

- [ ] Tool
- [ ] ..

## Get curators

Policy where they are paid

Campagin & Incentives:

- how to get curators to actually curate <= how to pay
- how tog et curators to actually ammend or suggest new schemas ... or even know they exist!

### MISSING

No time to write, but there need to be issues around all the other stuff in release plan around

- infrastructure
- migration
- incentives for other
- etc.

**Comment by bedeho** [comment]
# Rome Release (Redux)

## OKRs

### Introduce a better content system

- Members can make a creator profile and publish content under this profile.

- There is are content curators, policed by sudo.

- Launch with 3 content types.

- Add 1 new content type after release.

- Add a new schema for a content type, and migrate only some instances to the new schema.

### Engage community to understand Rome and join us in the future

- 50 new creator profiles.

- 10 curators in the working group.

- 1000 content uploads across all content categories.

## Tracking Issues

### Explainer: What is a tracking issue?

A tracking issue is a Github issue which **evolves**, and at any given time holds a list of TODO items, with a corresponding completion status and and possibly responsibility indicator (i.e. each item has one responsible actor). TODO items are grouped into tracking issues based on what most deeply facilitates effective collaboration and progress tracking..

### 1. New Infrastructure Runtime Modules

#### Description

Some core changes need to be done on the runtime to enable a new more flexible role infrastructure now and in the future.

#### Team

- @bedeho
- @mokhtar

#### Tasks

- staking module
  - [x] specify (@bedeho)
  - [ ] implement (@mokhtar)
- rewards module
  - [x] specify (@bedeho)
  - [ ] implement (@mokhtar)

### 2. Media System (Static Parts)

#### Description

This covers the base, or static, parts of the new media system.

#### Team

- @bedeho
- @alex
- @mokhtar

#### Tasks

- versioned data store module
  - [x] specify (@bedeho)
  - [ ] implement (@alex)
- content directory module "orchestrator": hiring & firing curators, permissions, policing/alerts, etc. <== some open questions
  - [ ] specify (@mokhtar)
  - [ ] implement (@mokhtar)
- add creator profile to membership module: <== perhaps creator profile should be outside of data store? worth discussing.
  - [ ] specify (@mokhtar)
  - [ ] implement (@mokhtar)
- Curator role in Pioneer
  - View status of curator group: list of actors, curation stats.
    - [ ] mockup
    - [ ] components & styling
    - [ ] state & backend integration
  - Joining flow
    - [ ] mockup
    - [ ] components & styling
    - [ ] state & backend integration
  - Policing flow
    - [ ] xxx

### 3. Media System (Dynamic Parts)

#### Description

The actual media system we chose to introduce at release, based on our new flexible runtime architecture, and how users interact with this in our primary app: Pioneer.

#### Team

- @martin
- @alex

#### Tasks

- [ ] 3 new content type schemas: Decide on actual type to support, based on availability of content and richness of schemas.
- [ ] Decide on new set of data_types required data directory.
- Define the following _for each type_ in Pioneer. (let each checkbox be status across all types)
  - Overview of subset of content directory for specific content type: no search for now, just pagination!
    - [ ] mockup
    - [ ] components & styling
    - [ ] state & backend integration
  - Item view & playback experience: different roles (creator, curator, viwer) may see different things
    - [ ] mockup
    - [ ] components & styling
    - [ ] state & backend integration
- A top level overview view of the entire directory: should we have featured content or creators?
    - [ ] mockup
    - [ ] components & styling
    - [ ] state & backend integration
- Creator profile in Pioneer
  - Extend membership flow: how you setup a creator profile
    - [ ] mockup
    - [ ] components & styling
    - [ ] state & backend integration
  - Publishing/unpublish flow for creator
    - [ ] mockup
    - [ ] components & styling
    - [ ] state & backend integration
  - Third party view of profile: e.g. see all content categorised, cover photo
    - [ ] mockup
    - [ ] components & styling
    - [ ] state & backend integration
  - Owner view + editing flow
    - [ ] mockup
    - [ ] components & styling
    - [ ] state & backend integration

### 4. Post-Release Media System Changes

#### Description

The essential design goal of the media system has been to allow versioned upgradability, and we have as such decided to execute on this.

#### Team

- @martin
- @alex

#### Tasks

- 1 new content type
  - [ ] decide on what
  - [ ] create new schema
  - [ ] update Pioneer to support new content type
- A new schema for existing concept
  - [ ] decide on what concept
  - [ ] create new schema for concept
  - [ ] ?create tool for migrating objects to new schema and run it.
  - [ ] update Pioneer

### 5. Launch New Substrate Chain

#### Description

We are launching a new Substrate chain because of X?.

#### Team

- @mokhtar

#### Tasks

- [ ] Set time for when old chain snapshot will be taken?
- Build tool to export old state and encoded as new GenesisConfig for new chain. Currently we have decided on
  - [ ]  Memberships
  - [ ] Accounts & balances in accounts
  - [ ] Data objects
  - [ ] Forum (all of it)
- [ ] Create GenesisConfig representations for all new schemas
- [ ] Update faucet server

### 6. Community Engagement Marketing

#### Description

What we do to get community to engage with the  

#### Team

- @martin
- <support crew, ben, finney, et.al..>
- @thomas (design)
- @bedeho

#### Tasks

- [ ] Integrate and finalise all specs into a network spec document. Arguably not best place to put this task... (@bedeho)
- Design incentive scheme for
 - [ ] creators
 - [ ] curators
 - [ ] update for any other existing role?: storage, validator, council
- [ ] Finalize the logomark for Rome
- New main page and live testnet page presentation
  - [ ] design
  - [ ] make
  - [ ] update status server (@mokhtar)
- Announce Rome
  - [ ] Write blog post
  - [ ] Write newsletter
  - [ ] Make assets needed for the two above
  - [ ] Update the (webflow) website with "next testnet section"
- Announce incentive system
  - [ ] Write new blog post
  - [ ] Make assets for post and promotion
- Announce launch of system
  - [ ] Write blog post
  - [ ] Write newsletter
  - [ ] Make assets needed for the two above
  - [ ] Deploy new website
- Write new/updated technical guides for
  - [ ] validator
  - [ ] storage provider
  - [ ] creator
  - [ ] curator
- [ ] Coordinating final launch communication with web3/parity
- [ ] Make support plan: who is "on call" at what time?

### 7. Release/Launch Operations

#### Description

All that is required to get the team done and product out the right way and to the right deadline!

#### Team

- `Everyone`

#### Tasks

- Create and publish a checklist of what needs to be tested for the
  - [ ] Sub-System Test
  - [ ] Final Test
- Do test
  - [ ] Sub-System Test
  - [ ] Final Test
- [ ] Make Launch checklist

**Comment by bedeho** [comment]
Has been put in production in Rome, closing.
